default_context:
  project_name: 'GEMSEC'
  project_slug: 'gemsec'
  domain_main: 'gemsec.edu'
  domain_staging: 'stag.gemsec.edu'
  docker_swarm_stack_name_main: 'gemsec-edu'
  docker_swarm_stack_name_staging: 'stag-gemsec-edu'
  secret_key: 'gseckey102938475'
  first_superuser: 'chris@cusys.io'
  first_superuser_password: 'chris_pass'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.gemsec.edu, https://stag.gemsec.edu, https://gemsec.edu, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@gemsec.edu'
  postgres_password: 'gemsec_pass'
  pgadmin_default_user: 'chris@cusys.io'
  pgadmin_default_user_password: 'chris_pass'
  traefik_constraint_tag: 'gemsec.edu'
  traefik_constraint_tag_staging: 'stag.gemsec.edu'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:chris_pass'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
